### ISSUE TITLE
Change the authentication method of players using Ely.by

### ISSUE THREAD

**Issue by Itsporo** [FIGRJA/combo_auth#10]
- Is there a way for players using ely.by accounts to bypass mojang's authentication server and go straight through ely.by's authentication server?
- Recently mojang's authentication server has had problems and affected a lot. Currently my players are having to spam join many times to get past mojang's authentication server to get to the second step which is through ely.by

**Comment by FIGRJA** [comment]
в последней версии **можно поменять** в конфигурации AuthList порядок серверов.
in the latest version, you **can change** the order of servers in the AuthList configuration.

**Comment by Itsporo** [comment]
> в последней версии **можно поменять** в конфигурации AuthList порядок серверов. in the latest version, you **can change** the order of servers in the AuthList configuration.
- So in theory, players using premium when entering the server will have to go through ely.by and then go to mojang, right?

**Comment by FIGRJA** [comment]
In theory , **yes** .In the future, I want to make sure that the mod saves the authentication server through which the player logged in

**Comment by Itsporo** [comment]
> In theory , **yes** .In the future, I want to make sure that the mod saves the authentication server through which the player logged in

- Ok thanks, I will try to change the config as you said to solve this problem
