### ISSUE TITLE
What happens if the player elyby uses the same nickname as the player mojang?

### ISSUE THREAD

**Issue by DearFox** [FIGRJA/combo_auth#9]
Does your mod have any settings or behavior for such cases?
 Or for the server it will be two different players with the same nickname but different uuid?

**Comment by FIGRJA** [comment]
as far as I understand, the uuid will always be different, and therefore they will be different for the server, but as for the commands, the last one that came has priority, and **no**, there are no settings in the mod about this ~~(yandex translate)~~
